glenn-syj/just-do-algorithms

celestedayoung/Week000/Week000_SWEA_1210_표다영.java
celestedayoung/Week000/Week000_SWEA_1859_표다영.java
celestedayoung/Week000/Week000_SWEA_1954_표다영.java
celestedayoung/Week000/Week000_백준_2810_표다영.java
celestedayoung/Week000/Week000_백준_2941_표다영.java

* 수정사항 참고해주세요
SWEA 문제 1210 Peek -> Solve
SWEA 문제 1859 Solve -> Peek

[ALG-000] SWEA 1210, 1859, 1954/ 백준 2810, 2941

---

Glenn-syj/Week000/Week000_SWEA_1210_손영준.java
Glenn-syj/Week000/Week000_SWEA_1859_손영준.java
Glenn-syj/Week000/Week000_SWEA_1954_손영준.java
Glenn-syj/Week000/Week000_SWEA_7272_손영준.java
Glenn-syj/Week000/Week000_백준_1592_손영준.java
Glenn-syj/Week000/Week000_백준_2810_손영준.java
Glenn-syj/Week000/Week000_백준_2941_손영준.java

[ALG-000] Merge 'Glenn-syj' into 'main'

[ALG-000] Merge 'Glenn-syj' into 'main'

---

minukHwang/Week001/Week001_SWEA_1289_황민욱.java
minukHwang/Week001/Week001_SWEA_1493_황민욱.java
minukHwang/Week001/Week001_SWEA_1940_황민욱.java
minukHwang/Week001/Week001_SWEA_2005_황민욱.java
minukHwang/Week001/Week001_SWEA_4698_황민욱.java
minukHwang/Week001/Week001_SWEA_4789_황민욱.java
minukHwang/Week001/Week001_SWEA_5356_황민욱.java
minukHwang/Week001/Week001_SWEA_6485_황민욱.java
minukHwang/Week001/Week001_백준_1158_황민욱.java

[ALG-001] Solve: SWEA/백준 문제 1289, 1493, 1940, 2005, 4698, 4789, 5356, 6485/ 1158번 풀이입니다.

[ALG-001] Solve: SWEA/백준 문제 1289, 1493, 1940, 2005, 4698, 4789, 5356, 6485/ 1158번 풀이

---

README.md
qkrrjsxor/Week002/src/boj_15828_박건택/Main.java
qkrrjsxor/Week002/src/boj_18258_박건택/Main.java

[ALG-002] Solve : 백준 15828, 18258

---

minukHwang/Week004/src/boj_1991_황민욱/Main.java
minukHwang/Week004/src/boj_2263_황민욱/Main.java
minukHwang/Week004/src/boj_24444_황민욱/Main.java
minukHwang/Week004/src/boj_24479_황민욱/Main.java
minukHwang/Week004/src/boj_9663_황민욱/Main.java
minukHwang/Week004/src/swea_1232_황민욱/Solution.java
minukHwang/Week004/src/swea_1974_황민욱/Solution.java
minukHwang/Week004/src/swea_2806_황민욱/Solution.java
minukHwang/Week004/src/swea_2814_황민욱/Solution.java
minukHwang/Week004/src/swea_2930_황민욱/Solution.java
minukHwang/Week004/src/swea_7964_황민욱/Solution.java

[ALG-004] Solve: SWEA/백준 문제 2930, 1232, 1974, 1991 /24479, 24444, 7964번 // Peek: SWEA 문제 2814번 // Try: 백준 문제 9663번 풀이입니다.

[ALG-004] Solve: SWEA/백준 문제 2930, 1232, 1974, 1991 /24479, 24444, 7964번 // Peek: SWEA 문제 2814번 // Try: 백준 문제 9663번 풀이

---

ucream-sh/Week004/src/boj_1991_트리순회/Main.java
ucream-sh/Week004/src/boj_2263_트리의순회/Main.java
ucream-sh/Week004/src/boj_24479_알고리즘수업_깊이우선탐색1/Main.java
ucream-sh/Week004/src/swea_2930_힙/Solution.java
ucream-sh/Week004/src/swea_7964_부먹왕국의차원관문/Solution.java

공가 사용으로 일정이 꼬여서 스터디도 참여를 못하고 힙 문제 외에는 다 Try라서 슬프네요.. 내일 다른 분들의 코드를 읽어보고 다시 도전해서 다 Solve하고 싶네요!
상 문제인 swea 2117 홈방범서비스를 풀이하지 못해서 하 문제들을 시도했었습니다.
[ALG-004] Solve: swea 2930 힙
[ALG-004] Try: boj 2263 트리의순회
[ALG-004] Try: boj 1991 트리순회
-> Try 상태로 코드제출했습니다. (구현을 못하는중입니다.) 둘 중 하나라도 풀면 둘 다 풀 수 있을 듯 합니다.
[ALG-004] Try: boj 24479 알고리즘수업 깊이우선탐색1
-> 테케는 맞게 출력되었으나 제출시 메모리초과.. 2차원배열로 구현하면 안되는듯합니다. 추가로 공부해서 필수였던 boj 24444 너비우선탐색 문제도 함께 구현해보겠습니다.
[ALG-004] Try: swea 7964 부먹왕국의차원관문
-> 테케 3개는 맞았는데 (13개중 3개정답) 런타임에러상태로 제출했습니다.

[ALG-004] Solve: swea 2930 // Try: boj 2263, boj 1991, boj 24479, swea 7964

---

celestedayoung/Week004/src/swea_1232_표다영/Solution.java
celestedayoung/Week004/src/swea_1974_표다영/Solution.java
celestedayoung/Week004/src/swea_2930_표다영/Solution.java
celestedayoung/Week004/src/swea_7964_표다영/Solution.java

[ALG-004] Solve: SWEA 1232, 1974, 2930, 7963 풀이

---

clare-u/Week006/src/boj_12865_유서현/Main.java
clare-u/Week006/src/boj_16236_유서현/Main.java
clare-u/Week006/src/boj_2096_유서현/Main.java
clare-u/Week006/src/boj_9935_유서현/Main.java

[ALG-006] Try: 백준 9935, 16236번 시도 / Peek: 백준 12865, 2096 peek로 풀이

---

undeadtimo/Week006/boj_12865_송창용/Main.java
undeadtimo/Week006/boj_16236_송창용/Main.java
undeadtimo/Week006/boj_9935_송창용/Main.java

자정까지 pull request 요청을 하였어야 했지만, 30분 늦었습니다.
시간 엄수하지 못한 점 죄송합니다.

[ALG-006] Peek: 백준 문제 12865번 풀이 / Solve: 백준문제 9935, 16236번 풀이

---

celestedayoung/Week006/src/boj_ 9935_표다영/Main.java
celestedayoung/Week006/src/boj_15686_표다영/Main.java
celestedayoung/Week006/src/boj_16236_표다영/Main.java

이번주는 더욱 더 정진하여 많은 문제를 풀겠습니다!
++두 문제 더 풀고 늦게라도 올립니다.

[ALG-006]  Solve: 백준문제 9935, 15686번 풀이 / Peek: 백준 문제 16236번

---

minukHwang/Week006/src/boj_12865_황민욱/Main.java
minukHwang/Week006/src/boj_15686_황민욱/Main.java
minukHwang/Week006/src/boj_16236_황민욱/Main.java
minukHwang/Week006/src/boj_9935_황민욱/Main.java

[ALG-006] Peek: 백준 문제 12865, 9935번 / Solve: 백준 문제 15686번 풀이 / Try: 백준 문제 16236번 시도입니다. (수정)

[ALG-006] Peek: 백준 문제 12865, 9935번 / Solve: 백준 문제 15686번 풀이 / Try: 백준 문제 16236번 시도

---

undeadtimo/Week007/boj_14501_송창용/Main.java
undeadtimo/Week007/boj_15685_송창용/Main.java
undeadtimo/Week007/boj_16928_송창용/Main.java

이번주차 알고리즘 풀이 제출합니다.
형식과 내용이 올바른지 확인 부탁드립니다.

[ALG-007] Solve: 백준 문제 14501번 풀이 / Peek: 백준 문제 15685번, 16928번 풀이

---

celestedayoung/Week007/src/boj_14501_표다영/Main.java
celestedayoung/Week007/src/boj_15685_표다영/Main.java
celestedayoung/Week007/src/boj_16928_표다영/Main.java

[ALG-007] Solve: 백준 문제 14501, 15685, 16928 풀이

---

celestedayoung/Week008/src/boj_1149_표다영/Main.java
celestedayoung/Week008/src/boj_1197_표다영/Main.java
celestedayoung/Week008/src/boj_12851_표다영/Main.java
celestedayoung/Week008/src/boj_12851_표다영/Main.md
celestedayoung/Week008/src/boj_20040_표다영/Main.java

peek한 문제에 대해 자세한 내용을 md 파일로 작성해보았습니다. 앞으로도 이러한 방식으로 공부해보겠습니다.

[ALG-008] Solve: 백준 문제 1197, 20040, 1149 풀이 / Peek: 백준 문제 12851 풀이

---

undeadtimo/Week008/boj_1197_송창용/Main.java
undeadtimo/Week008/boj_12851_송창용/Main.java
undeadtimo/Week008/boj_17404_송창용/Main.java
undeadtimo/Week008/boj_20040_송창용/Main.java

내용과 양식에 올바르지 않은 점이 있는지 확인 부탁드립니다.
추후, 풀지 못한 두 문제에 대해 추가로 풀이를 작성하여 재제출하겠습니다.

[ALG-008] Solve: 백준 문제 20040번 풀이 / Peek: 백준 문제1197, 12851, 17404번 풀이

---

clare-u/Week008/src/boj_12851_숨바꼭질2/Main.java
clare-u/Week008/src/boj_12851_숨바꼭질2/Main.md

이번주에는 1문제를 peek한 이후 개인적으로 풀이한 알고리즘들을 이슈로 게시하였습니다. 
https://github.com/Glenn-syj/just-do-algorithms/issues/133 까지 같이 봐주시면 감사하겠습니다.

[ALG-008] Peek: 백준 12851 peek로 풀이, md 파일 게시

---

minukHwang/Week009/src/swea_1949_황민욱/Solution.java
minukHwang/Week009/src/swea_1953_황민욱/Solution.java
minukHwang/Week009/src/swea_2117_황민욱/Solution.java
minukHwang/Week009/src/swea_2383_황민욱/Solution.java
minukHwang/Week009/src/swea_2383_황민욱/Solution.md
minukHwang/Week009/src/swea_4008_황민욱/Solution.java
minukHwang/Week009/src/swea_5644_황민욱/Solution.java

[ALG-009] Solve: SWEA 문제 1949, 1953, 2117, 2383, 4008, 5644번 풀이입니다.

[ALG-009] Solve: SWEA 문제 1949, 1953, 2117, 2383, 4008, 5644번 풀이

---

qkrrjsxor/Week010/src/boj_1005_박건택/Main.java
qkrrjsxor/Week010/src/boj_2252_박건택/Main.java
qkrrjsxor/Week010/src/boj_2252_박건택/Main.md
qkrrjsxor/Week010/src/boj_4386_박건택/Main.java
qkrrjsxor/Week010/src/boj_4386_박건택/Main.md

Solve : boj_2252_줄세우기 ,  boj_1005_ACMCraft
Peek : boj_4386_별자리만들기
Docs : boj_2252_줄세우기, boj_4386_별자리만들기

[ALG-010] Solve : boj_2252,  boj_1005/ Peek : boj_4386

---

celestedayoung/Week010/src/boj_17472_표다영/Main.java
celestedayoung/Week010/src/boj_2252_표다영/Main.java
celestedayoung/Week010/src/boj_4386_표다영/Main.java

17472문제 디버깅 감사드립니다 영준님! 해당 문제에 대해 분석한 md 파일도 추후에 올리겠습니다.

[ALG-010] Solve: 백준2252, 4386 문제 풀이 / Peek: 17472 문제 풀이

---

clare-u/Week010/src/boj_1005_유서현/Main.java
clare-u/Week010/src/boj_2252_유서현/Main.java
clare-u/Week010/src/boj_4386_유서현/Main.java

10주차에는 3문제를 풀이해보았습니다. 위상정렬과 구현에 대한 좋은 연습이 되었습니다.

[ALG-010] Solve: 백준 2252번 풀이 / Peek: 백준 4386, 1005번 풀이

---

undeadtimo/Week010/boj_1005_송창용/Main.java
undeadtimo/Week010/boj_2252_송창용/Main.java
undeadtimo/Week010/boj_4386_송창용/Main.java

10주차 문제 풀이 작성합니다.
양식과 내용이 문제가 없는지 확인 부탁드립니다.

[ALG-010] Solve: BOJ 1005, 2252, 4386 풀이

---

celestedayoung/Week011/src/boj_19237_표다영/Main.java
celestedayoung/Week011/src/boj_19237_표다영/Main.md

상어 시리즈 문제가 도움이 되어 더 어려운 상어 문제도 풀어볼 예정입니다.

[ALG-011] Peek: BOJ 문제 19237 문제 풀이

---

clare-u/Week011/src/boj_16946_유서현/Main.java
clare-u/Week011/src/boj_16946_유서현/Main.md

11주차에는 벽부수고 이동하기 4번을 풀이하고 md파일을 작성해보았습니다. 작성 중 한번 파일을 날려먹어서 분량이 약간 줄었습니다.

[ALG-011] Peek: BOJ 문제 16946번 풀이

---

minukHwang/Week011/src/boj_19237_황민욱/Main.java
minukHwang/Week011/src/boj_4803_황민욱/Main.java
minukHwang/Week011/src/boj_4803_황민욱/Main.md

[ALG-011] Try: BOJ 문제 19237번 // Peek: BOJ 문제 4803번 풀이입니다.
금주 취업 활동 외 개인 일정으로 늦어져서 죄송합니다. 
배려해주셔서 감사합니다!!

[ALG-011] Try: BOJ 문제 19237번 // Peek: BOJ 문제 4803번 풀이

---

celestedayoung/Week012/src/prgm_258712_표다영/Solution.java
celestedayoung/Week012/src/prgm_258712_표다영/Solution.md

PRGM 문제 258712번 가장 많이 받은 선물에 대한 코드와 풀이법에 대한 md 파일을 작성했습니다.

[ALG-012] Solve: PRGM 문제 258712번 풀이

---

clare-u/Week013/src/boj_14940_유서현/Main.java
clare-u/Week013/src/boj_14940_유서현/Main.md
clare-u/Week014/src/boj_9663_N_Queen/Main.java
clare-u/Week014/src/boj_9663_N_Queen/Main.md

n-Queen 문제를 peek라도 드디어 풀어 더욱 뿌듯하네요.

[ALG-013] Solve: BOJ 문제 14940번 풀이, [ALG-014] Peek: BOJ 문제 9663번 풀이

---

minukHwang/Week_013/src/boj_2606_황민욱/Main.java
minukHwang/Week_013/src/boj_2606_황민욱/Main.md
minukHwang/Week_014/src/boj_2573_황민욱/Main.java
minukHwang/Week_014/src/boj_2573_황민욱/Main.md

[ALG-013] Solve: BOJ 문제 2606번 풀이, [ALG-014] Solve: BOJ 문제 2573번 풀이입니다!

[ALG-013] Solve: BOJ 문제 2606번 풀이, [ALG-014] Solve: BOJ 문제 2573번 풀이

---

qkrrjsxor/Week013/src/swea_1244_박건택/Solution.java
qkrrjsxor/Week013/src/swea_1244_박건택/Solution.md
qkrrjsxor/Week014/src/swea_3234_박건택/Solution.java
qkrrjsxor/Week014/src/swea_3234_박건택/Solution.md

[ALG-013] Solve: SWEA 문제 1244번 풀이, [ALG-014] Peek: SWEA 문제 3234번 풀이

---

celestedayoung/Week013/src/swea_2105_표다영/Solution.java
celestedayoung/Week013/src/swea_2105_표다영/Solution.md
celestedayoung/Week014/src/swea_1949_표다영/Solution.java
celestedayoung/Week014/src/swea_1949_표다영/Solution.md

풀었던 문제 중 괜찮다고 생각한 문제를 다시 풀며 복습했습니다.

[ALG-013] Solve: SWEA 문제 2105 풀이, [ALG-014] Solve: SWEA 문제 1949 풀이
